### ISSUE TITLE
Organisms' search is skewed towards the center chunk

### ISSUE THREAD

**Issue by ChadSki** [z-van-baars/fishtank#10]
Organisms should search all 9 chunks at the same time.

```
+---+---+---+
|   |   |   |
+---+---+---+
|   | X |   |
+---+---+---+
|   |   |   |
+---+---+---+
```

Currently, the center chunk is searched first. When an organism is near the edge of a chunk, there might be closer targets in the outer 8 chunks.

**Comment by ChadSki** [comment]
Also, goblins seem to prefer going up to going down.

**Comment by z-van-baars** [comment]
Fixed this issue, however the program seems to be running much slower now.  I've made other changes, so I'm not entirely sure it's related.
